name: continous trainig
on: 
  push:
    branches:
      - workflow_continous_trainig
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: Why to run this
        required: false
        default: running CT
permissions:                    # Global permissions configuration starts here
  contents: write               # 'read' access to repository contents
  pull-requests: write 
  deployments: write
  actions: write
jobs:
  continous-trainig:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{secrets.SERVICE_ACCOUNT_KEY}}
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl.dvc -f -r model-tracker
          dvc unprotect model/model.pkl
          dvc repro -f 
          echo "Training completed"
          dvc add model/model.pkl -r model-tracker --to-remote
          dvc push model/model.pkl.dvc -f -r model-tracker
      - name: Commit .dvc file changes
        run: |
          git config --local user.email "simonjaramillovelez@hotmail.com"
          git config --local user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Upgrading model serialization"
      - uses: ad-m/github-push-action@master
        with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            branch: ${{github.ref}}
      - uses: iterative/setup-cml@v1
      - name: Push metrics 
        env: 
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cat report.txt >> report.md
          cml-comment prediction-behavior.png --md >> report.md
          cml-send-comment report.md



